spring:
  application:
    name: @name@
    description: @description@
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
endpoints:
  sensitive: false
---
server:
  port: 8101
---
logging:
  config: classpath:logback.xml
  file: /var/log/@artifactId@/@artifactId@.log
---
cbr:
  url: http://www.cbr.ru/scripts/XML_daily.asp
  fields:
    required:
---
spring:
  boot:
    admin:
      url: http://127.0.0.1:8300
